# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ac1339e70cb84a048b04ae908bfd0698"
name = "LAA Custom App"
handle = "laa-custom-app"
application_url = "https://physical-surf-analog-installed.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "laa-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_discounts,read_draft_orders,read_orders,read_payment_terms,read_products,read_shipping,unauthenticated_read_checkouts,unauthenticated_read_content,unauthenticated_read_customer_tags,unauthenticated_read_customers,unauthenticated_read_metaobjects,unauthenticated_read_product_inventory,unauthenticated_read_product_listings,unauthenticated_read_product_pickup_locations,unauthenticated_read_product_tags,unauthenticated_read_selling_plans,unauthenticated_write_checkouts,unauthenticated_write_customers,write_customers,write_discounts,write_draft_orders,write_products"

[auth]
redirect_urls = [
  "https://physical-surf-analog-installed.trycloudflare.com/auth/callback",
  "https://physical-surf-analog-installed.trycloudflare.com/auth/shopify/callback",
  "https://physical-surf-analog-installed.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[app_proxy]
url = "https://physical-surf-analog-installed.trycloudflare.com/a/checkout"
subpath = "checkout"
prefix = "a"

[pos]
embedded = false
